version: '3'
services:
    api_service:
        image: flask-app:latest
        labels:
            - "traefik.http.routers.api_service.rule=Host(`api_service.docker.localhost`)"

    reverse_proxy:
        image: traefik
        command: 
            - --providers.docker=true  
            - --entrypoints.web.address=:80
        ports:
            - "80:80"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"

