version: '3'
services:
    api_service:
        image: flask-app:latest

    reverse_proxy:
        image: "nginx:1.19.9-alpine"
        restart: always
        depends_on:
            - api_service
        ports:
            - "8080:80"
        volumes:
            - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
